var a = parseInt (prompt("Enter a salary of a:"));
var b = parseInt (prompt("Enter a salary of b:"));
var c = parseInt (prompt("Enter a salary of c:"));
var d = parseInt (prompt("Enter a salary of d:"));
var e = parseInt (prompt("Enter a salary of e:"));
var total = a+b+c+d+e;
var avg = parseInt (prompt("Enter a salary of f:"));
var salary = avg*6;
var finalTotal = salary - total;
alert(finalTotal);
